routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// //TEST REDIS
// Route::get('/visits', function () {
//
// dd(App\ProductsCategories::find(23)->fields->first()->name);
//
// });





Route::get('/stripe/charge', function () {
    $invoices = App\DealInvoice::all();

    return view('stripe.charge')->withInvoices($invoices);
});
Route::post('/stripe/charge', 'StripeController@charge');



Route::post('stripe/webhook', 'StripeWebhookController@handle');


Route::get('/', 'HomepageController@home');

//TEST
Route::get('/login-test/{id}', function ($id) {
    Auth::loginUsingId($id);
    return redirect()->back();
});

Route::get('/notifications/test', function () {
  Auth::user()->notify(new \App\Notifications\Business\Welcome);
  return redirect()->back();
});

//Authenticate Links
Auth::routes();
Route::get('/join', function () {
  return redirect('business/register');
});
Route::get('business/register', 'Auth\RegisterBusinessController@showRegistrationForm');
Route::post('business/register', 'Auth\RegisterBusinessController@register');
Route::get('/auth/{provider}', 'Auth\SocialController@redirectToProvider');
Route::get('/auth/callback/{provider}', 'Auth\SocialController@handleProviderCallback');

//Verified Email
Route::get('/verify/{token}', 'UserController@verifiedEmail');

//Referral invitation
Route::get('/invite/{ref}', 'ReferController@invite');


//Authenticate users has access
Route::group(['middleware' => 'auth'], function(){

  //Account Settings
  Route::get('account/settings', 'UserController@accountSettings');
  Route::post('account/settings/password/update', 'UserController@updatePassword');
  Route::post('account/settings/email/update', 'UserController@updateEmail');
  Route::post('account/settings/payout/update', 'UserController@updatePayoutMethods');

  //Notifications
  Route::get('notifications/read/{notification_id}', 'NotificationsController@read');
  Route::get('notifications/markasread', 'NotificationsController@markAsRead');

  //Bids
  Route::get('delivery/{request}/bid/create', 'BidController@create');
  Route::post('delivery/{request}/bid/create', 'BidController@store');

  //Conversation
  Route::get('conversations', 'ConversationController@index');
  Route::get('conversations/{conversation}', 'ConversationController@single');
  Route::post('conversations/{conversation}/sendMessage', 'ConversationController@sendMessage');

  //Deal
  Route::get('deal/{invoice}', 'DealController@index');

});

//Only admin has access
// **For now is auth, change it before public in admin**
Route::group(['middleware' => 'admin'], function(){



  //Products Categories
  Route::get('admin/categories', 'ProductsCategoriesController@index');
  Route::get('admin/categories/create', 'ProductsCategoriesController@create');
  Route::post('admin/categories/create', 'ProductsCategoriesController@store');
  Route::get('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@edit');
  Route::post('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@update');
  Route::get('admin/categories/{productsCategories}/delete', 'ProductsCategoriesController@destroy');
  Route::get('admin/categories/{productsCategories}/restore', 'ProductsCategoriesController@restore');

  Route::get('admin/businesses/index', 'AdminController@businesses');
  Route::get('admin/clients/index', 'AdminController@users');
  Route::get('admin/payments/index', 'AdminController@payments');
  Route::get('admin/products/index', 'AdminController@products');

  Route::get('admin/products/feature/add/{product}', 'FeaturedProductsController@add');
  Route::get('admin/products/feature/remove/{product}', 'FeaturedProductsController@remove');
  Route::get('feature', 'FeaturedProductsController@getAllFeatured');

});

//Only business has access
Route::group(['middleware' => 'business'], function(){

  //  Dashboard view only for businesses
  Route::get('/dashboard', "BusinessController@dashboard");

  //Themes
  Route::get('business/themes', 'BusinessThemeController@themes');
  Route::post('business/themes', 'BusinessThemeController@updateThemes');
  Route::get('/business/themes/customise', 'BusinessThemeController@customise');
  Route::post('/business/themes/customise/frontpageslider', 'BusinessThemeController@updateFrontPageSlider');
  Route::post('/business/themes/customise/homepage', 'BusinessThemeController@updateHomePage');
  Route::post('/business/themes/customise/aboutpage', 'BusinessThemeController@updateAboutPage');


  //Products
  Route::get('business/products', 'ProductsController@index');
  Route::get('business/products/create', 'ProductsController@create');
  Route::post('business/products/create', 'ProductsController@store');
  Route::get('business/products/{products}/edit', 'ProductsController@edit');
  Route::post('business/products/{products}/edit', 'ProductsController@update');
  Route::get('business/products/{products}/delete', 'ProductsController@destroy');
  Route::get('business/products/{products}/images', 'ProductsController@images');
  Route::post('business/products/{products}/images/add', 'ProductsController@addImages');
  Route::post('business/products/{products}/images/remove', 'ProductsController@removeImages');



  //Stores
  Route::get('business/stores', 'StoresController@index');
  Route::get('business/stores/create', 'StoresController@create');
  Route::post('business/stores/create', 'StoresController@store');
  Route::get('business/stores/{stores}/edit', 'StoresController@edit');
  Route::post('business/stores/{stores}/edit', 'StoresController@update');
  Route::get('business/stores/{stores}/delete', 'StoresController@destroy');


  //ProductsStores
  //store
  Route::get('business/stores/{stores}/products', 'ProductsStoresController@storeProducts');
  Route::get('business/stores/{stores}/products/{product}/add', 'ProductsStoresController@storeAddProduct');
  Route::get('business/stores/{stores}/products/{product}/remove', 'ProductsStoresController@storeRemoveProduct');
  //product
  Route::get('business/products/{products}/stores', 'ProductsStoresController@productStores');
  Route::get('business/products/{products}/stores/{store}/add', 'ProductsStoresController@productAddStore');
  Route::get('business/products/{products}/stores/{store}/remove', 'ProductsStoresController@productRemoveStore');

  //Discount
  Route::get('business/discount/create', 'ProductsDiscountController@create');
  Route::post('business/discount/create', 'ProductsDiscountController@store');
  Route::get('business/discount/{productsDiscount}/remove', 'ProductsDiscountController@destroy');


  //Profile
  Route::get('/business/profile/edit', 'BusinessController@edit');
  Route::post('/business/profile/edit', 'BusinessController@update');
  Route::get('/business/account/payout', 'BusinessController@payout');
  Route::get('/business/account/email', 'BusinessController@changeEmail');
  Route::get('/business/account/password', 'BusinessController@changePwd');

  //Shopping carts
  Route::get('/business/carts', 'ClientRequestController@index');
  Route::get('/business/carts/open', 'ClientRequestController@openCarts');
  Route::get('/business/carts/completed', function(){
    return view('carts.business-closed');
  });
  Route::get('/business/carts/{invoice}/invoice', 'DealController@businessInvoice');
  Route::get('/business/carts/{request}/bid', 'BidController@businessCreate');
  Route::get('/business/carts/{request}/view', 'ShoppingCartController@businessView');

  Route::get('/business/card', 'StripeController@creditCard');
  Route::post('/business/card', 'StripeController@updateCreditCard');


  //Subscription
  Route::get('/business/subscription', 'StripeController@index');
  Route::get('/business/subscription/change', 'StripeController@change_subscription');
  Route::patch('/business/subscription/change', 'StripeController@changePlan');

  Route::delete('/stripe/subscribe', 'StripeController@destroy');
  Route::patch('/stripe/subscribe', 'StripeController@update');

});

Route::get('/stripe/subscribe', function () {
    $plans = App\SubscribePlan::all();

    return view('stripe.subscribe')->withPlans($plans);
});
Route::post('/stripe/subscribe', 'StripeController@register');

//Only clients has access
Route::group(['middleware' => 'client'], function(){
  // Dashboard
  Route::get('/client/dashboard', 'ClientController@dashboard');
  //Profile
  Route::get('/client/profile/edit', 'ClientController@edit');
  Route::post('/client/profile/edit', 'ClientController@update');
  Route::get('/client/profile/settings', 'UserController@accountSettings');
  Route::get('/client/profile/email', 'UserController@changeEmail');
  Route::get('/client/profile/pwd', 'UserController@changePwd');
  Route::get('/client/profile/payout', 'UserController@changePayout');

  //Meeting points
  Route::get('/client/meeting_points', 'MeetingPointsController@index');
  Route::post('/client/meeting_points/create', 'MeetingPointsController@store');
  Route::get('/client/meeting_points/{meeting_points}/delete', 'MeetingPointsController@destroy');
  Route::post('/client/meeting_points/{meeting_points}/edit', 'MeetingPointsController@update');

  //Shopping Cart
  Route::post('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::get('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::post('/products/{product}/addSearchedItemToCart', 'ItemsController@searchAdd');
  Route::get('/item/{item}/remove', 'ItemsController@destroy');
  Route::get('/shopping_cart', 'ShoppingCartController@index');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Wishlist;
use Redis;

class Products extends Model
{
  use SoftDeletes;
  use Wishlist;

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'products';

  protected $softDelete = true;


  public function getSlugAttribute(): string
  {
    return str_slug($this->name);
  }

  public function getUrlAttribute(): string
  {
      return action('ProductsController@single', [$this->id, $this->slug]);
  }

  public function getCurrentpriceAttribute(): string
  {
    if($this->discount){
      $price = $this->discount->new_price;
    }else {
      $price = $this->price;
    }

    return number_format($price, 2, '.', '');
  }

  public function getTagsstringAttribute(): string
  {
    $tags_string = $this->tags()->pluck('name')->implode(', ');

    return $tags_string;
  }

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'name',
    'description',
    'long_description',
    'price',
    'bag',
    'weight',
    'height',
    'width',
    'depth',
    'picture',
    'video',
    'category_id',
    'business_id',
    'status',
    'has_stock'
  ];

  /**
  * Return the relationship with Business model.
  */
  public function business()
  {
    return $this->belongsTo('App\Business', 'business_id');
  }

  /**
  * Return the relationship with Category model.
  */
  public function category()
  {
    return $this->belongsTo('App\ProductsCategories', 'category_id');
  }

  public function tags()
  {
    return $this->BelongsToMany('App\Tags', 'products_tags', 'product_id', 'tag_id');
  }

  public function stores()
  {
    return $this->BelongsToMany('App\Stores', 'products_stores', 'product_id', 'store_id');
  }

  public function hasStore($store)
  {
    return $this->stores()->where('store_id', $store->id)->first()!=null;
  }

  public function syncStores($stores)
  {
    return $this->stores()->sync($stores);
  }

  /**
   * Get the discount record associated with the product.
   */
  public function discount()
  {
      return $this->hasOne('App\ProductsDiscount', 'product_id', 'id');
  }

  public function scopeLive()
  {

    return \DB::table('products')
                ->whereExists(function ($query1) {
                    $query1->select(\DB::raw(1))
                          ->from('business')
                          ->whereRaw('business.id = products.business_id')
                          ->whereRaw('business.status <> "offline"');
                })
                ->get();

    // return $query->where('status', 'live')->orWhere('status', 'edited')->get();
  }

  public function items()
  {
    return $this->hasMany('App\Items', 'product_id');
  }

  public function isFeatured()
  {
    return Redis::zscore('featured', $this->id);
  }

  public function scopeFeatures($query)
  {

    $ids = Redis::zrange('featured', 0, -1);

    // $features = Products::hydrate(
    //   array_map('json_decode', $features)
    // );

    $features = self::whereIn('id', $ids)->get();

    // dd($features);
    return $features;
  }

  public function images()
  {
    $images = Redis::smembers('product'.$this->id.'images');

    return $images;

  }


}

app/Theme.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Theme extends Model
{
  /**
   * Don't auto-apply mass assignment protection.
   *
   * @var array
   */
  protected $guarded = [];

  public function getSlugAttribute(): string
  {
    return strtolower($this->name).".main";
  }

}

resources/views/all.blade.php
@extends('layouts.boilerplate')

@section('head')
	@include('partials.head')
@endsection

@section('og-scripts')
@endsection

@section('head-scripts')
@endsection

@section('navbar')
	@include('partials.navbar')
	<button type="button" class="quick-action-btn visible-xs">
		<i class="pe-7s-keypad pe-3x pe-va"></i>
	</button>

	@include('partials.quick-action')
@endsection

@section('body')
	<div class="container first">
		<h1 class="w300">
			<i class="icon icon-shopping-cart"></i> My shopping carts
		</h1>
		<p class="s-13em">
			Shopping carts work differently in Shopguin. For every company that sells on Shopguin, you get to make a shopping cart specifically with them. You can then individually request a deliverer or conventional delivery method, for the delivery of your items. If you need some more help, click here.
		</p>
		<div class="row">
			<div class="col-lg-9">
				<div class="row">
					@foreach($shopping_carts as $cart)
						<div class="col-md-6">
							<div class="shopping-cart-panel box-shadow">
								<div class="shopping-cart-heading">
									<div class="row">
										<div class="col-md-10 col-xs-10">
											{{$cart->business->name}} ({{$cart->items->count()}})
										</div>
										<div class="col-md-2 col-xs-2 text-right">
											<a href="/shopping_cart/{{$cart->id}}/remove" class="c-red">
												<i class="icon icon-rubbish-bin"></i>

											</a>
										</div>
									</div>
								</div>
								<div class="shopping-cart-body">
									<ul class="products-as-list">
										@foreach($cart->items as $item)
											<li>
												<div class="row">
													<div class="col-md-3 col-xs-3">
														<img class="img-responsive" src="https://placeimg.com/790/640/tech">
													</div>
													<div class="col-md-9 col-xs-9">
														<div class="row">
															<div class="col-md-10 col-xs-9">
																<h4>
																	{{$item->product->name}}
																</h4>
																<h6>
																	<b>Qty:</b> {{$item->qty}} | € {{$item->price}}
																</h6>

															</div>
															<div class="col-md-2 col-xs-3 text-right">
																<a href="/item/{{$item->id}}/remove" style="font-size:1.2em; margin-right:10px;">
																	<i class="fa fa-times-circle fa-1x " aria-hidden="true"></i>
																</a>
															</div>
														</div>
													</div>
												</div>
											</li>

										@endforeach
									</ul>
									<div class="row">
										<div class="col-md-9 col-xs-7">
											<h3 class="" style="margin:1px;">
												Total:
												<span class="c-black">
													€{{$cart->price}}
												</span>
												&nbsp; &nbsp;

											</h3>
										</div>
										<div class="col-md-3 col-xs-5">
											<a href="/client/request/{{$cart->id}}/create" class="btn btn-primary" style="display: inline-block;">
												Request
												<i class="icon icon-right-chevron"></i>
											</a>

										</div>
									</div>
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>
			<div class="col-lg-3 side-info">
				<h3>
					Instructions
				</h3>
				<p class="s-13em">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
			</div>
		</div>
	</div>
@endsection


@section('footer')
	@include('partials.footer')
@endsection

@section('scripts')
	@include('partials.scripts')
	<script type="text/javascript" src="/js/products/products.js"></script>
@endsection

resources/views/dashboard.blade.php
@include('dashboard.head')

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			@include('dashboard.nav')


			<!-- page content -->
			<div class="right_col" role="main">
				<div class="">
					<div class="page-title">
				 		<div class="title_left">
					 		<h3>Welcome {{Auth::user()->profile->name}}</h3>
				  		</div>


					</div>
					<div class="clearfix"></div>
					<div class="row">
						<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="tile-stats">
								<div class="icon"><i class="fa fa-users"></i>
							</div>
							@if(array_key_exists("total", $visits))
								<div class="count">{{$visits['total']}}</div>
							@else
								<div class="count">0</div>
							@endif
							<h3>Number of visitors</h3>
							<p>Number of visitors for your business on Shopguin.</p>
							</div>
						</div>
						<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="tile-stats">
								<div class="icon"><i class="fa fa-shopping-cart"></i>
							</div>
							<div class="count">{{Auth::user()->profile->openCarts()}}</div>
							<h3>New shopping carts</h3>
							<p>Number of open shopping carts currently with your business.</p>
							</div>
						</div>
						<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="tile-stats">
								<div class="icon"><i class="fa fa-gift"></i>
							</div>
							<div class="count">{{Auth::user()->profile->products->count()}}</div>
							<h3>Number of products</h3>
							<p>Number of products currently listed with your business on Shopguin.</p>
							</div>
						</div>
						<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="tile-stats">
								<div class="icon"><i class="fa fa-map-marker"></i>
							</div>
							<div class="count">{{Auth::user()->profile->stores->count()}}</div>
							<h3>Number of stores</h3>
							<p>Number of stores listed for your business on Shopguin.</p>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div class="x_panel">
								<div class="x_title">
									<h2>Overview of my business</h2>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="demo-container" style="height:280px">
											<div id="totalProductSales" class="demo-placeholder"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="x_panel">
								<div class="x_title">
									<h2>Getting started</h2>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<p class="text-muted font-13 m-b-30">
										Have a look at the list below of what you need to fill in, to get maximise the most out of Shopguin!
									</p>
									<div class="">
										<ul class="to_do">
											<li>
												Choose a theme for my business
											</li>
											<li>
												Customise the fields in my chosen theme
											</li>
											<li>
												List my products on Shopguin
											</li>
											<li>
												List my stores on Shopguin
											</li>
											{{-- @foreach($visits as $key => $value)
											<li>
												{{$key}}: {{($value)}}
												<br>
											</li>
											@endforeach --}}
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			@include('dashboard.footer')
		</div>
	</div>

	@include('dashboard.scripts')
	<script type="text/javascript" src="/js/dashboard/frontpage.js"></script>
	<script type="text/javascript" src="/js/assets/jquery.flot.min.js"></script>
	<script type="text/javascript" src="/js/assets/jquery.flot.time.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	 <div class="row">
		  <div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					 <div class="panel-heading">Dashboard</div>
					 <div class="panel-body">
						  You are logged in!
						  <br><br>
						  <strong>Businesses</strong>
						  <br>
						  @foreach($business as $b)
							 <a href="/{{$b->slug}}">{{$b->name}}</a><br>
						  @endforeach

					 </div>
				</div>
		  </div>
	 </div>
</div>

<div class="container">
	 <div class="row">
		  <div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					 <div class="panel-heading">Admin (Permission only for admins later)</div>
					 <div class="panel-body">
						<a href="/admin/categories/" class="btn btn-default">Categories</a><br>
					 </div>
				</div>
		  </div>
	 </div>
</div>
@endsection

resources/views/wishlist.blade.php
@extends('layouts.boilerplate')

@section('head')
	<title>My wishlist - Shopguin</title>
	@include('partials.head')
@endsection

@section('og-scripts')
@endsection

@section('head-scripts')
@endsection

@section('navbar')
	@include('partials.navbar')
@endsection

@section('body')
	<div class="container first">
		<h1 class="w300">
			<i class="pe-7s-magic-wand pe-lg pe-va" ></i>
			My Wishlist
		</h1>
		<p class="s-13em">
			Everything you want to buy in the future in one place. When you are ready just add them to your cart!
		</p>
		<div class="row">
			<div class="col-lg-7">
				<ul class="products-as-list">
					<li>
						<div class="row">
							@foreach($wishlist as $product)
							<div class=" col-xs-12 col-sm-6 col-md-6">
								<div class="row">
									<div class="col-md-2 col-xs-3">
									<img class="img-responsive" src="/storage/{{$product->picture}}">
										</br>
									</div>
									<div class="col-md-10 col-xs-9">
										<h4>
											<a href="/products/{{$product->id}}">
											{{$product->name}}
											</a>
											<a href="/wishlist/{{$product->id}}/remove" class="delete">
												<i class="icon icon-rubbish-bin"></i>
											</a>
										</h4>
										<h6>
											<i class="icon icon-euro"></i>
											€ {{$product->currentprice}}
										</h6>
										<div class="row">
											<div class="col-xs-6">
												<form method="POST" action="/products/{{$product->id}}/addItemToCart">
													{{ csrf_field() }}
													<button type="submit" class="btn btn-xs btn-primary">Add to cart</button>
												</form>
											</div>
										</div>
										<hr>
									</div>
								</div>
							</div>
							@endforeach
						</div>
					</li>
				</ul>
			</div>
			<div class="col-lg-2"></div>
			<div class="col-lg-3 side-info">
					<h3 class="w300">
						Instructions
					</h3>
					<p class="s-11em">
						You can add as many products as you want in your personal wishlist. Simply press on the heart shaped icon below the product. You can then access all the products in your wishlist here.
					</p>
				</div>
		</div>
	</div>
@endsection


@section('footer')
	@include('partials.footer')
@endsection

@section('scripts')
	@include('partials.scripts')
	<script type="text/javascript" src="/js/products/products.js"></script>
@endsection