routes/web.php
Route::get('/login-test/{id}', function ($id) {
    Auth::loginUsingId($id);
    return redirect()->back();
});

Route::get('/notifications/test', function () {
  Auth::user()->notify(new \App\Notifications\Business\Welcome);
  return redirect()->back();
});

//Authenticate Links
Auth::routes();
Route::get('/join', function () {
  return redirect('business/register');
});
Route::get('business/register', 'Auth\RegisterBusinessController@showRegistrationForm');
Route::post('business/register', 'Auth\RegisterBusinessController@register');
Route::get('/auth/{provider}', 'Auth\SocialController@redirectToProvider');
Route::get('/auth/callback/{provider}', 'Auth\SocialController@handleProviderCallback');

//Verified Email
Route::get('/verify/{token}', 'UserController@verifiedEmail');

//Referral invitation
Route::get('/invite/{ref}', 'ReferController@invite');


//Authenticate users has access
Route::group(['middleware' => 'auth'], function(){

  //Account Settings
  Route::get('account/settings', 'UserController@accountSettings');
  Route::post('account/settings/password/update', 'UserController@updatePassword');
  Route::post('account/settings/email/update', 'UserController@updateEmail');
  Route::post('account/settings/payout/update', 'UserController@updatePayoutMethods');

  //Notifications
  Route::get('notifications/read/{notification_id}', 'NotificationsController@read');
  Route::get('notifications/markasread', 'NotificationsController@markAsRead');

  //Bids
  Route::get('delivery/{request}/bid/create', 'BidController@create');
  Route::post('delivery/{request}/bid/create', 'BidController@store');

  //Conversation
  Route::get('conversations', 'ConversationController@index');
  Route::get('conversations/{conversation}', 'ConversationController@single');
  Route::post('conversations/{conversation}/sendMessage', 'ConversationController@sendMessage');

  //Deal
  Route::get('deal/{invoice}', 'DealController@index');

});

//Only admin has access
// **For now is auth, change it before public in admin**
Route::group(['middleware' => 'admin'], function(){



  //Products Categories
  Route::get('admin/categories', 'ProductsCategoriesController@index');
  Route::get('admin/categories/create', 'ProductsCategoriesController@create');
  Route::post('admin/categories/create', 'ProductsCategoriesController@store');
  Route::get('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@edit');
  Route::post('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@update');
  Route::get('admin/categories/{productsCategories}/delete', 'ProductsCategoriesController@destroy');
  Route::get('admin/categories/{productsCategories}/restore', 'ProductsCategoriesController@restore');

  Route::get('admin/businesses/index', 'AdminController@businesses');
  Route::get('admin/clients/index', 'AdminController@users');
  Route::get('admin/payments/index', 'AdminController@payments');
  Route::get('admin/products/index', 'AdminController@products');

  Route::get('admin/products/feature/add/{product}', 'FeaturedProductsController@add');
  Route::get('admin/products/feature/remove/{product}', 'FeaturedProductsController@remove');
  Route::get('feature', 'FeaturedProductsController@getAllFeatured');

});

//Only business has access
Route::group(['middleware' => 'business'], function(){

  //  Dashboard view only for businesses
  Route::get('/dashboard', "BusinessController@dashboard");

  //Themes
  Route::get('business/themes', 'BusinessThemeController@themes');
  Route::post('business/themes', 'BusinessThemeController@updateThemes');
  Route::get('/business/themes/customise', 'BusinessThemeController@customise');
  Route::post('/business/themes/customise/frontpageslider', 'BusinessThemeController@updateFrontPageSlider');
  Route::post('/business/themes/customise/homepage', 'BusinessThemeController@updateHomePage');
  Route::post('/business/themes/customise/aboutpage', 'BusinessThemeController@updateAboutPage');


  //Products
  Route::get('business/products', 'ProductsController@index');
  Route::get('business/products/create', 'ProductsController@create');
  Route::post('business/products/create', 'ProductsController@store');
  Route::get('business/products/{products}/edit', 'ProductsController@edit');
  Route::post('business/products/{products}/edit', 'ProductsController@update');
  Route::get('business/products/{products}/delete', 'ProductsController@destroy');
  Route::get('business/products/{products}/images', 'ProductsController@images');
  Route::post('business/products/{products}/images/add', 'ProductsController@addImages');
  Route::post('business/products/{products}/images/remove', 'ProductsController@removeImages');



  //Stores
  Route::get('business/stores', 'StoresController@index');
  Route::get('business/stores/create', 'StoresController@create');
  Route::post('business/stores/create', 'StoresController@store');
  Route::get('business/stores/{stores}/edit', 'StoresController@edit');
  Route::post('business/stores/{stores}/edit', 'StoresController@update');
  Route::get('business/stores/{stores}/delete', 'StoresController@destroy');


  //ProductsStores
  //store
  Route::get('business/stores/{stores}/products', 'ProductsStoresController@storeProducts');
  Route::get('business/stores/{stores}/products/{product}/add', 'ProductsStoresController@storeAddProduct');
  Route::get('business/stores/{stores}/products/{product}/remove', 'ProductsStoresController@storeRemoveProduct');
  //product
  Route::get('business/products/{products}/stores', 'ProductsStoresController@productStores');
  Route::get('business/products/{products}/stores/{store}/add', 'ProductsStoresController@productAddStore');
  Route::get('business/products/{products}/stores/{store}/remove', 'ProductsStoresController@productRemoveStore');

  //Discount
  Route::get('business/discount/create', 'ProductsDiscountController@create');
  Route::post('business/discount/create', 'ProductsDiscountController@store');
  Route::get('business/discount/{productsDiscount}/remove', 'ProductsDiscountController@destroy');


  //Profile
  Route::get('/business/profile/edit', 'BusinessController@edit');
  Route::post('/business/profile/edit', 'BusinessController@update');
  Route::get('/business/account/payout', 'BusinessController@payout');
  Route::get('/business/account/email', 'BusinessController@changeEmail');
  Route::get('/business/account/password', 'BusinessController@changePwd');

  //Shopping carts
  Route::get('/business/carts', 'ClientRequestController@index');
  Route::get('/business/carts/open', 'ClientRequestController@openCarts');
  Route::get('/business/carts/completed', function(){
    return view('carts.business-closed');
  });
  Route::get('/business/carts/{invoice}/invoice', 'DealController@businessInvoice');
  Route::get('/business/carts/{request}/bid', 'BidController@businessCreate');
  Route::get('/business/carts/{request}/view', 'ShoppingCartController@businessView');

  Route::get('/business/card', 'StripeController@creditCard');
  Route::post('/business/card', 'StripeController@updateCreditCard');


  //Subscription
  Route::get('/business/subscription', 'StripeController@index');
  Route::get('/business/subscription/change', 'StripeController@change_subscription');
  Route::patch('/business/subscription/change', 'StripeController@changePlan');

  Route::delete('/stripe/subscribe', 'StripeController@destroy');
  Route::patch('/stripe/subscribe', 'StripeController@update');

});

Route::get('/stripe/subscribe', function () {
    $plans = App\SubscribePlan::all();

    return view('stripe.subscribe')->withPlans($plans);
});
Route::post('/stripe/subscribe', 'StripeController@register');

//Only clients has access
Route::group(['middleware' => 'client'], function(){
  // Dashboard
  Route::get('/client/dashboard', 'ClientController@dashboard');
  //Profile
  Route::get('/client/profile/edit', 'ClientController@edit');
  Route::post('/client/profile/edit', 'ClientController@update');
  Route::get('/client/profile/settings', 'UserController@accountSettings');
  Route::get('/client/profile/email', 'UserController@changeEmail');
  Route::get('/client/profile/pwd', 'UserController@changePwd');
  Route::get('/client/profile/payout', 'UserController@changePayout');

  //Meeting points
  Route::get('/client/meeting_points', 'MeetingPointsController@index');
  Route::post('/client/meeting_points/create', 'MeetingPointsController@store');
  Route::get('/client/meeting_points/{meeting_points}/delete', 'MeetingPointsController@destroy');
  Route::post('/client/meeting_points/{meeting_points}/edit', 'MeetingPointsController@update');

  //Shopping Cart
  Route::post('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::get('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::post('/products/{product}/addSearchedItemToCart', 'ItemsController@searchAdd');
  Route::get('/item/{item}/remove', 'ItemsController@destroy');
  Route::get('/shopping_cart', 'ShoppingCartController@index');
  Route::get('/shopping_cart/{shopping_cart}/remove', 'ShoppingCartController@destroy');
  Route::get('/shopping_cart/added/success/{shopping_cart}', 'ClientRequestController@continue');

  //Wishlist
  Route::post('/wishlist/{product}/add', 'WishlistController@add');
  Route::get('/wishlist/{product}/add', 'WishlistController@add');
  Route::get('/wishlist/{product}/remove', 'WishlistController@remove');
  Route::get('/wishlist', 'WishlistController@index');

  //Request
  Route::get('/client/request/{shopping_cart}/create', 'ClientRequestController@create');
  Route::post('/client/request/{shopping_cart}/create', 'ClientRequestController@store');
  Route::get('/client/request/{request}/view', 'BidController@view');

  // Deliveries
  Route::get('/client/deliveries', function(){
    return view('deliver.home');
  });
  Route::get('/client/deliveries/{delivery_id}', function(){
    return view('deliver.single');
  });

app/Theme.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Theme extends Model
{
  /**
   * Don't auto-apply mass assignment protection.
   *
   * @var array
   */
  protected $guarded = [];

  public function getSlugAttribute(): string
  {
    return strtolower($this->name).".main";
  }

}

resources/views/dashboard/footer.blade.php
{{-- Footer --}}
<footer>
	<div class="pull-right">
		&copy; 2017, Shopguin Ltd. | 
		Template by <a href="https://colorlib.com">Colorlib</a>
	</div>
	<div class="clearfix"></div>
</footer>

resources/views/dashboard/head.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Shopguin - Dashboard</title>
	<!-- Font Awesome -->
	<script src="https://use.fontawesome.com/67b15a84b6.js"></script>
	<!-- NProgress -->
	<link href="/css/assets/nprogress.css" rel="stylesheet">
	{{-- DataTables --}}
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
	{{-- Country selector --}}
	<link rel="stylesheet" href="/css/assets/countrySelect.min.css">
	<!-- Custom Theme Style -->
	<link href="/css/gent-dashboard.css" rel="stylesheet">
	<link rel="stylesheet" href="/css/assets/datepicker.css">
	<link rel="stylesheet" href="/css/assets/datepicker.css">
	<link rel="stylesheet" href="/css/assets/smart_wizard.min.css">
	{{-- Favicon --}}
	<link rel="icon" type="img/ico" href="icon/favicon.ico">
	<link rel="icon" sizes="1024x1025" href="icon/favicon.png">
	<link rel="apple-touch-icon-precomposed" sizes="1024x1025" href="img/ios-favicon.png" />
	<!-- Scripts -->
	<script>
		window.Laravel = {!! json_encode([
			'csrfToken' => csrf_token(),
		]) !!};
	</script>

</head>

resources/views/dashboard/nav.blade.php
{{-- Side navigation --}}
<div class="col-md-3 left_col">
	<div class="left_col scroll-view">
		<div class="navbar nav_title" style="border: 0;">
			<a href="/" class="site_title">

				<span>
					<img src="/img/logo-and-text-white.png" class="img-responsive nav-logo" style="margin: 10px;">
					{{-- Shopguin Dashboard --}}
				</span>
			</a>
		</div>

		<div class="clearfix"></div>

		{{-- Profile information --}}
		<div class="profile clearfix">
			<div class="profile_pic">
				<img src="/storage/{{Auth::user()->profile->logo}}" class="img-circle profile_img">
			</div>
	  		<div class="profile_info">
				<span>Welcome,</span>
		 		<h2>{{Auth::user()->profile->name}}</h2>
	  		</div>
	  		<div class="clearfix"></div>
		</div>

		<br />

		{{-- Sidebar menu --}}
		<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
			<div class="menu_section">
				<h3>General</h3>
				<ul class="nav side-menu">
					<li><a href="/{{Auth::user()->profile->slug}}"><i class="fa fa-shopping-bag"></i>Go to my store</a></li>
					<li><a href="/dashboard"><i class="fa fa-home"></i>Home</a></li>
					<li><a><i class="fa fa-user"></i> Account <span class="fa fa-chevron-down"></span></a>
						<ul class="nav child_menu">
							<li><a href="/business/profile/edit">Edit profile</a></li>
							<li><a href="/business/account/payout">Payout methods</a></li>
							<li><a href="/business/account/email">Change email</a></li>
							<li><a href="/business/account/password">Change password</a></li>
						</ul>
					</li>
					<li><a><i class="fa fa-calendar"></i> Subscription <span class="fa fa-chevron-down"></span></a>
						<ul class="nav child_menu">
							<li><a href="/business/subscription/change">My Subscription</a></li>
							<li><a href="/business/card">Credit Card</a></li>
							<li><a href="/business/subscription">Cancel</a></li>
						</ul>
					</li>
					<li><a><i class="fa fa-paint-brush" aria-hidden="true"></i>Theme <span class="fa fa-chevron-down"></span></a>
						<ul class="nav child_menu">
							<li><a href="/business/themes">Choose your theme</a></li>
							<li><a href="/business/themes/customise">Customise theme</a></li>
						</ul>
					</li>
					<li><a><i class="fa fa-gift" ></i> Products <span class="fa fa-chevron-down"></span></a>
				  		<ul class="nav child_menu">
							<li><a href="/business/products">All products</a></li>
							<li><a href="/business/products/create">Add a new product</a></li>
							<li><a href="/business/discount/create">Add a product discount</a></li>
						</ul>
					</li>

					<li><a><i class="fa fa-map-marker" aria-hidden="true"></i>Stores <span class="fa fa-chevron-down"></span></a>
				  		<ul class="nav child_menu">
							<li><a href="/business/stores">All stores</a></li>
							<li><a href="/business/stores/create">Add a new store</a></li>
						</ul>
					</li>
					<li><a><i class="fa fa-shopping-cart" ></i> Shopping carts <span class="fa fa-chevron-down"></span></a>
						<ul class="nav child_menu">
							<li><a href="/business/carts">View all carts</a></li>
						</ul>
					</li>

				</ul>
			</div>
		</div>

		{{-- /menu footer buttons --}}

	</div>
</div>


{{-- Top Navigation --}}
<div class="top_nav">
	<div class="nav_menu">
		<nav>
			<div class="nav toggle">
				<a id="menu_toggle"><i class="fa fa-bars"></i></a>
			</div>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
						<img src="/storage/{{Auth::user()->profile->logo}}" >{{Auth::user()->profile->name}}
						<span class=" fa fa-angle-down"></span>
					</a>
					<ul class="dropdown-menu dropdown-usermenu pull-right">
						<li><a href="/business/profile/edit"> Profile</a></li>
						<li>
							<a href="{{ route('logout') }}"
									onclick="event.preventDefault();
													 document.getElementById('logout-form').submit();">
									<i class="fa fa-sign-out pull-right"></i> Log Out</a>
							</a>

							<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									{{ csrf_field() }}
							</form>
						</li>
					</ul>
				</li>
				<li role="presentation" class="dropdown">
					<a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
						<i class="fa fa-envelope-o"></i>
						@if(($numNot = Auth::user()->unreadNotifications->count()) != 0 )
						<span class="badge bg-green">{{$numNot}}</span>
						@endif
					</a>
					<ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
						@foreach(Auth::user()->unreadNotifications as $notification)
						<li>

							<a href="/notifications/read/{{$notification->id}}">
								<span class="glyphicon glyphicon-off"></span>
								<span>
									<span>{{$notification->type}}</span>
									
								</span>
								<span class="message">
									{{$notification->data['message']}}
									<span class="time">{{$notification->created_at->diffForHumans()}}</span>
								</span>
							</a>
						</li>
						@endforeach
						<li>
							<div class="text-center">
								<a href="/notifications/markasread">
									<strong>Mark as Read</strong>
									<i class="fa fa-angle-right"></i>
								</a>
							</div>
						</li>
						<li>
							<div class="text-center">
								<a href="/notifications/test">
									<strong>Create Test Notification</strong>
									<i class="fa fa-angle-right"></i>
								</a>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>

resources/views/dashboard/scripts.blade.php
<script type="text/javascript" src="/js/assets/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/js/assets/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/js/assets/fastclick.js"></script>

<script type="text/javascript" src="/js/dashboard/dashboard.js"></script>

<!-- NProgress -->
<script src="/js/assets/nprogress.js"></script>
<script src="/js/assets/bootstrap-datepicker.js"></script>