routes/web.php
// **For now is auth, change it before public in admin**
Route::group(['middleware' => 'admin'], function(){



  //Products Categories
  Route::get('admin/categories', 'ProductsCategoriesController@index');
  Route::get('admin/categories/create', 'ProductsCategoriesController@create');
  Route::post('admin/categories/create', 'ProductsCategoriesController@store');
  Route::get('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@edit');
  Route::post('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@update');
  Route::get('admin/categories/{productsCategories}/delete', 'ProductsCategoriesController@destroy');
  Route::get('admin/categories/{productsCategories}/restore', 'ProductsCategoriesController@restore');

  Route::get('admin/businesses/index', 'AdminController@businesses');
  Route::get('admin/clients/index', 'AdminController@users');
  Route::get('admin/payments/index', 'AdminController@payments');
  Route::get('admin/products/index', 'AdminController@products');

  Route::get('admin/products/feature/add/{product}', 'FeaturedProductsController@add');
  Route::get('admin/products/feature/remove/{product}', 'FeaturedProductsController@remove');
  Route::get('feature', 'FeaturedProductsController@getAllFeatured');

});

//Only business has access
Route::group(['middleware' => 'business'], function(){

  //  Dashboard view only for businesses
  Route::get('/dashboard', "BusinessController@dashboard");

  //Themes
  Route::get('business/themes', 'BusinessThemeController@themes');
  Route::post('business/themes', 'BusinessThemeController@updateThemes');
  Route::get('/business/themes/customise', 'BusinessThemeController@customise');
  Route::post('/business/themes/customise/frontpageslider', 'BusinessThemeController@updateFrontPageSlider');
  Route::post('/business/themes/customise/homepage', 'BusinessThemeController@updateHomePage');
  Route::post('/business/themes/customise/aboutpage', 'BusinessThemeController@updateAboutPage');


  //Products
  Route::get('business/products', 'ProductsController@index');
  Route::get('business/products/create', 'ProductsController@create');
  Route::post('business/products/create', 'ProductsController@store');
  Route::get('business/products/{products}/edit', 'ProductsController@edit');
  Route::post('business/products/{products}/edit', 'ProductsController@update');
  Route::get('business/products/{products}/delete', 'ProductsController@destroy');
  Route::get('business/products/{products}/images', 'ProductsController@images');
  Route::post('business/products/{products}/images/add', 'ProductsController@addImages');
  Route::post('business/products/{products}/images/remove', 'ProductsController@removeImages');



  //Stores
  Route::get('business/stores', 'StoresController@index');
  Route::get('business/stores/create', 'StoresController@create');
  Route::post('business/stores/create', 'StoresController@store');
  Route::get('business/stores/{stores}/edit', 'StoresController@edit');
  Route::post('business/stores/{stores}/edit', 'StoresController@update');
  Route::get('business/stores/{stores}/delete', 'StoresController@destroy');


  //ProductsStores
  //store
  Route::get('business/stores/{stores}/products', 'ProductsStoresController@storeProducts');
  Route::get('business/stores/{stores}/products/{product}/add', 'ProductsStoresController@storeAddProduct');
  Route::get('business/stores/{stores}/products/{product}/remove', 'ProductsStoresController@storeRemoveProduct');
  //product
  Route::get('business/products/{products}/stores', 'ProductsStoresController@productStores');
  Route::get('business/products/{products}/stores/{store}/add', 'ProductsStoresController@productAddStore');
  Route::get('business/products/{products}/stores/{store}/remove', 'ProductsStoresController@productRemoveStore');

  //Discount
  Route::get('business/discount/create', 'ProductsDiscountController@create');
  Route::post('business/discount/create', 'ProductsDiscountController@store');
  Route::get('business/discount/{productsDiscount}/remove', 'ProductsDiscountController@destroy');


  //Profile
  Route::get('/business/profile/edit', 'BusinessController@edit');
  Route::post('/business/profile/edit', 'BusinessController@update');
  Route::get('/business/account/payout', 'BusinessController@payout');
  Route::get('/business/account/email', 'BusinessController@changeEmail');
  Route::get('/business/account/password', 'BusinessController@changePwd');

  //Shopping carts
  Route::get('/business/carts', 'ClientRequestController@index');
  Route::get('/business/carts/open', 'ClientRequestController@openCarts');
  Route::get('/business/carts/completed', function(){
    return view('carts.business-closed');
  });
  Route::get('/business/carts/{invoice}/invoice', 'DealController@businessInvoice');
  Route::get('/business/carts/{request}/bid', 'BidController@businessCreate');
  Route::get('/business/carts/{request}/view', 'ShoppingCartController@businessView');

  Route::get('/business/card', 'StripeController@creditCard');
  Route::post('/business/card', 'StripeController@updateCreditCard');


  //Subscription
  Route::get('/business/subscription', 'StripeController@index');
  Route::get('/business/subscription/change', 'StripeController@change_subscription');
  Route::patch('/business/subscription/change', 'StripeController@changePlan');

  Route::delete('/stripe/subscribe', 'StripeController@destroy');
  Route::patch('/stripe/subscribe', 'StripeController@update');

});

Route::get('/stripe/subscribe', function () {
    $plans = App\SubscribePlan::all();

    return view('stripe.subscribe')->withPlans($plans);
});
Route::post('/stripe/subscribe', 'StripeController@register');

//Only clients has access
Route::group(['middleware' => 'client'], function(){
  // Dashboard
  Route::get('/client/dashboard', 'ClientController@dashboard');
  //Profile
  Route::get('/client/profile/edit', 'ClientController@edit');
  Route::post('/client/profile/edit', 'ClientController@update');
  Route::get('/client/profile/settings', 'UserController@accountSettings');
  Route::get('/client/profile/email', 'UserController@changeEmail');
  Route::get('/client/profile/pwd', 'UserController@changePwd');
  Route::get('/client/profile/payout', 'UserController@changePayout');

  //Meeting points
  Route::get('/client/meeting_points', 'MeetingPointsController@index');
  Route::post('/client/meeting_points/create', 'MeetingPointsController@store');
  Route::get('/client/meeting_points/{meeting_points}/delete', 'MeetingPointsController@destroy');
  Route::post('/client/meeting_points/{meeting_points}/edit', 'MeetingPointsController@update');

  //Shopping Cart
  Route::post('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::get('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::post('/products/{product}/addSearchedItemToCart', 'ItemsController@searchAdd');
  Route::get('/item/{item}/remove', 'ItemsController@destroy');
  Route::get('/shopping_cart', 'ShoppingCartController@index');
  Route::get('/shopping_cart/{shopping_cart}/remove', 'ShoppingCartController@destroy');
  Route::get('/shopping_cart/added/success/{shopping_cart}', 'ClientRequestController@continue');

  //Wishlist
  Route::post('/wishlist/{product}/add', 'WishlistController@add');
  Route::get('/wishlist/{product}/add', 'WishlistController@add');
  Route::get('/wishlist/{product}/remove', 'WishlistController@remove');
  Route::get('/wishlist', 'WishlistController@index');

  //Request
  Route::get('/client/request/{shopping_cart}/create', 'ClientRequestController@create');
  Route::post('/client/request/{shopping_cart}/create', 'ClientRequestController@store');
  Route::get('/client/request/{request}/view', 'BidController@view');

  // Deliveries
  Route::get('/client/deliveries', function(){
    return view('deliver.home');
  });
  Route::get('/client/deliveries/{delivery_id}', function(){
    return view('deliver.single');
  });

  // Bids
  Route::get('/client/bids', function(){
    return view('bid.home');
  });
  Route::get('/client/bids/{bid}', function(){
    return view('bid.single');
  });

  //Bid
  Route::post('bid/{bid}/accept', 'BidController@acceptBid');

});

// Products (Client view)
Route::get('/products/{product}/{slug?}', 'ProductsController@single');
Route::get('/products', 'ProductsController@all');


//Show Client Profile
Route::get('/client/{client}', 'ClientController@show');

//Client Requests
Route::get('/delivery', 'ClientRequestController@all');
Route::get('/delivery/{request}', 'ClientRequestController@index');


// Search
Route::get('/search', function(){
  $data = [
    'products' => []
  ];
  return view('products.search', $data);
});
Route::post('/search', 'ProductsController@search');

// Placeholder development routes
Route::get('/dev1', function(){
   $data = [
    'id' => '2'
  ];
  return view('agnolotti.main', $data);
});

Route::get('/dev3', function(){
   $data = [
    'id' => '2'
  ];
  return view('vionnet.main', $data);
});

Route::get('/dev4', function(){
  $data = [
    'url' => 'business/2/'
  ];
  return view('vionnet.products', $data);
});

Route::get('/dev5', function(){
  return view('carts.single-business');
});

// Landing page
Route::get('/business', function(){
  return view('businesses.landing');
});
Route::get('/aboutus', function(){
  return view('misc.aboutus');
});

Route::get('/tsandcs', function(){
  return view('misc.tsandcs');
});

Route::get('/retailers', 'BusinessController@retailers');
Route::get('/themes', 'HomepageController@themes');
Route::get('/howto', 'HomepageController@howto');
Route::get('/howto/account', 'HomepageController@howto_account');
Route::get('/howto/addproduct', 'HomepageController@howto_addproduct');
Route::get('/howto/themes', 'HomepageController@howto_themes');

Route::get('/demo/{theme}', 'BusinessController@demo');

//Always on bottom of the file

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\FollowBusiness;
use App\Traits\Wishlist;

class Client extends Model
{
  use SoftDeletes;
  use FollowBusiness;
  use Wishlist;


  protected $table = "client";

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'first_name',
    'last_name',
    'picture',
    'gender',
    'birthday',
    'about',
    'country',
    'user_id',
    'phone',
    'stripe_id',
  ];

  public function getNameAttribute(): string
  {
    return $this->first_name.' '.$this->last_name;
  }

  public function getOrdersAttribute(): string
  {
    return $this->shoppingCarts()->count() + $this->requests()->count();
  }

  public function getDeliversAttribute(): string
  {
    return $this->bids()->count();
  }

  /**
  * Return the relationship with User model.
  */
  public function user()
  {
    return $this->belongsTo('App\User', 'user_id');
  }

  /**
  * Return the meeting points than client create.
  */
  public function meetingPoints()
  {
    return $this->hasMany('App\MeetingPoints');
  }

  /**
  * Return the wishlist than client create.
  */
  public function shoppingCarts()
  {
    return $this->hasMany('App\ShoppingCart');
  }

  /**
  * Return the requests than client create.
  */
  public function requests()
  {
    return $this->hasMany('App\ClientRequest');
  }

  public function bids()
  {
    return $this->morphMany('App\Bid', 'biddable');
  }


}

app/Http/Controllers/ClientRequestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ClientRequest;
use App\ShoppingCart;
use Auth;
use Illuminate\Support\Facades\DB;

class ClientRequestController extends Controller
{

    /**
     * Where to redirect
     *
     * @var string
     */
    protected $redirectTo = '/';

    private $form_rules = [
      'meeting_point'  => '',
      'address1'  => 'required_if:meeting_point,null',
      'country' => 'required_if:meeting_point,null',
      'city'  => 'required_if:meeting_point,null'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ClientRequest $request)
    {
      $business_id = Auth::user()->profile->id;

      $allRequests = ClientRequest::whereHas('business', function($q) use ($business_id) {
        $q->where('id', '=', $business_id);
      })->get();

      $openRequests = ClientRequest::whereHas('business', function($q) use ($business_id) {
        $q->where('id', '=', $business_id);
      })->where('status', '=', 'open')->get();

      $closedRequests = ClientRequest::whereHas('business', function($q) use ($business_id) {
        $q->where('id', '=', $business_id);
      })->where('status', '=', 'close')->get();

      $data = [
        'allRequests' => $allRequests,
        'openRequests' => $openRequests,
        'closedRequests' => $closedRequests
      ];

      return view('carts.index', $data);
    }

    public function openCarts(ClientRequest $request)
    {
      $business_id = Auth::user()->profile->id;
      $openRequests = ClientRequest::whereHas('business', function($q) use ($business_id) {
        $q->where('id', '=', $business_id);
      })->where('status', '=', 'open')->get();
      return view('carts.business-open')->with('requests', $openRequests);
    }

    public static function permissionCheck(ShoppingCart $shopping_cart)
    {
      $client = Auth::user()->profile;

      if(!$shopping_cart->belongsToClient($client)){
        abort(404);
      }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(ShoppingCart $shopping_cart)
    {
      $client = Auth::user()->profile;

      $this->permissionCheck($shopping_cart);

      return view('client_request.create')->with('shopping_cart', $shopping_cart);
    }

    public function continue(ShoppingCart $shopping_cart)
    {
      $client = Auth::user()->profile;

      $this->permissionCheck($shopping_cart);

      return view('carts.addtocart-success')->with('shopping_cart', $shopping_cart);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, ShoppingCart $shopping_cart)
    {
      //for check
      $client = Auth::user()->profile;

      $this->permissionCheck($shopping_cart);

      if (Auth::check()){
              $v = \Validator::make($request->all(), $this->form_rules);
      }

      if ($v->fails()) {
              return redirect()->back()->withErrors($v);
      }

      //Complete all queries before commited
      DB::beginTransaction();


      if(!$meeting_point_id = $request['meeting_point']){

        $meeting_point_id = $client->meetingPoints()->create([
          'address1'  => $request['address1'],
          'address2'  => $request['address2'],
          'state'  => $request['state'],
          'post_code' => $request['post_code'],
          'country'  => $request['country'],
          'city'  => $request['city'],
          'map_x' => $request['map_x'],
          'map_y'  => $request['map_y'],
        ])->id;
      }

      $client_request = ClientRequest::create([
        'client_id'   => $client->id,
        'business_id'  => $shopping_cart->business->id,
        'meeting_point_id' => $meeting_point_id,
        'message'   =>  $request['message'],
        'total_price' => $shopping_cart->price
      ]);

      $shopping_cart->createRequest($client_request);

      $shopping_cart->business->user->notify(new \App\Notifications\Business\NewOrder);

      //Commit the transaction
      DB::commit();

      return redirect($this->redirectTo);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function all()
    {
      $requests = ClientRequest::open();

      return view('deliver.requests')->withRequests($requests);
    }


}

resources/views/client_request/_create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	 <div class="row">
		  <div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					 <div class="panel-heading">Make Request</div>
					 <div class="panel-body">
						 <strong>{{$shopping_cart->business->name}}</strong>
						 <hr>
						 items: {{$shopping_cart->items->count()}}
						 <br>
						 @foreach($shopping_cart->items as $item)
						 	{{$item->product->name}} | qty: {{$item->qty}} | price {{$item->price}}
							<br>
						 @endforeach
						 <br>
						 Total Price: {{$shopping_cart->price}}

						 <form class="form-horizontal" role="form" method="POST" action="/client/request/{{$shopping_cart->id}}/create">
						 {{ csrf_field() }}

						 <div class="form-group{{ $errors->has('meeting_point') ? ' has-error' : '' }}">
							 <label for="meeting_point" class="col-md-4 control-label">Meeting Point</label>
							 <div class="col-md-6">
								 <select name="meeting_point" class="form-control">
								 @foreach(auth()->user()->profile->meetingPoints as $mp)
								 <option value="{{$mp->id}}">{{$mp->address}}</option>
								 @endforeach
								 </select>
							 </div>
						 </div>

						 <div class="form-group{{ $errors->has('message') ? ' has-error' : '' }}">
							 <label for="message" class="col-md-4 control-label">Message</label>
							 <div class="col-md-6">
								 <input id="message" type="text" class="form-control" value="{{ old('message') }}" name="message">

								 @if ($errors->has('message'))
								 <span class="help-block">
								 <strong>{{ $errors->first('message') }}</strong>
								 </span>
								 @endif
							 </div>
						 </div>


						 <div class="form-group">
							 <div class="col-md-8 col-md-offset-4">
								 <button type="submit" class="btn btn-primary">
								 Make Request
								 </button>
							 </div>
						 </div>

					 </form>

					 </div>
				</div>
		  </div>
	 </div>
</div>

@endsection

resources/views/client_request/create.blade.php
@extends('layouts.boilerplate')

@section('head')
	@include('partials.head')
	<link rel="stylesheet" href="/css/assets/datepicker.css">
	<link rel="stylesheet" href="/css/assets/jquery.timepicker.css">
@endsection

@section('og-scripts')
@endsection

@section('head-scripts')
@endsection

@section('navbar')
	@include('partials.navbar')
	@include('partials.quick-action')
@endsection

@section('body')
	<div class="container first">
		<h1 class="w300">
			Shopping cart for {{$shopping_cart->business->name}}
		</h1>
		<p class="s-13em">
			Use this page to choose a delivery address for your shopping cart, and also leave a message for your deliverer if you like. You will then receive bids on your shopping cart, for you to choose from. Once you've found your ideal bid, you can accept it and then pay for it.
		</p>
	</div>
	<div class="container">
		<div class="row">
			{{-- Current product for shopping cart --}}
			<div class="col-md-8 col-md-offset-2 box-light">
				{{-- Timeline steps --}}
				<div style="margin-bottom: 75px; margin-top: 15px;">
					<ul class="timeline-steps">
						<li class="active">
							<i class="icon icon-price-tag"></i>
							<span>Products</span>
						</li>
						<li>
							<i class="icon icon-placeholder"></i>
							<span>Location</span>
						</li>
						<li>
							<i class="icon icon-route"></i>
							<span>Finalise</span>
						</li>

						<div class="progress-bar" style="width: 0%;"></div>
						<div class="bar"></div>
					</ul>
				</div>
				<form role="form" id="clientRequest" method="POST" action="/client/request/{{$shopping_cart->id}}/create" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="form-multistep">
						{{-- Products --}}
						<div class="step" id="step1">
							<h3 class="w500">
								Shopping cart overview
							</h3>
							<div class="row">
								<div class="col-md-12">
									<div class="box-light">
										<h4 class="w500" style="margin-top: 0;">
											{{$shopping_cart->business->name}} ({{$shopping_cart->items->count()}} items)
										</h4>
										<hr>
										<ul class="products-as-list">
											<div class="row">
												@foreach($shopping_cart->items as $item)
												<div class="col-md-12">
													<li>
														<div class="row">
															<div class="col-md-2 col-sm-3 col-xs-3">
																<img class="img-responsive" src="/storage/{{$item->product->picture}}">
															</div>
															<div class="col-md-10 col-sm-9 col-xs-9">
																<h4>
																	<div class="row">
																		<div class="col-md-9 col-xs-12">
																			{{$item->product->name}}
																		</div>
																		<div class="col-md-3 text-right hidden-xs">
																			<a href="/item/{{$item->id}}/remove" class="delete">
																				<i class="icon icon-rubbish-bin"></i> Remove
																			</a>
																		</div>
																	</div>
																</h4>
																<h6>
																	<b>Qty:</b>
																	{{$item->qty}}
																	{{-- <label for="qty"></label>
																	<input  class="input-sm" type="number" min="1" step="1" value="{{$item->qty}}" name="qty" style="display: inline-block; width: 75px;"> --}}
																</h6>
																<h6>
																	€ {{$item->price}}
																	<a href="/item/{{$item->id}}/remove" class="btn btn-xs btn-red hidden-md hidden-lg" style="position: absolute; right: 5px;">
																		<i class="icon icon-rubbish-bin"></i> Remove
																	</a>
																</h6>
															</div>
														</div>
													</li>
												</div>
												@endforeach
											</div>

										</ul>
										<h3 class="info no-vm">
											<span>
												<i class="icon icon-euro"></i>
												Total
											</span>
											€ {{$shopping_cart->price}}
										</h3>
									</div>

								</div>

							</div>

							<button type="button" id="to-location" class="btn btn-primary" data-dismiss="alert">
								Next
								<i class="icon icon-right-chevron"></i>
							</button>
							</br></br>
						</div>
						{{-- Location --}}
						<div class="step" id="step2" style="display: none;">
							<h3 class="w500">
								Delivery location
							</h3>
							<p class="s-12em">
								Please either choose from one of your meeting points saved in your profile, or enter a new delivery location.
							</p>
							<div class="row">
								<div class="col-md-10 col-md-offset-1">
									<h4 class="w500 accordion" data-toggle="collapse" data-target="#newaddress">
										<i class="fa fa-angle-right" aria-hidden="true"></i>
										Choose a new address
									</h4>
									<div id="newaddress" class="collapse">
										<label for="address" class="">Search for address</label>
										<input type="text" name="address" class="" id="address" placeholder="" onFocus="geolocate()">
										<hr>

										<div class="row">
											<div class="col-md-6">
												<label for="street_number" class="">Address line 1</label>
												<input name="address1" type="text" class="" id="street_number" placeholder="" value="Enter address here">
											</div>
											<div class="col-md-6">
												<label for="route" class="">Address line 2</label>
												<input name="address2" type="text" class="" id="route" placeholder="">
											</div>
											<div class="col-md-6">
												<label for="locality" class="">City</label>
												<input name="city" type="text" class="" id="locality" placeholder="">
											</div>
											<div class="col-md-6">
												<label for="administrative_area_level_1" class="">State</label>
												<input name="state" type="text" class="" id="administrative_area_level_1" placeholder="">
											</div>
											<div class="col-md-6">
												<label for="country" class=" ">Country</label>
												<input name="country" type="text" class="" id="country" placeholder="">
											</div>
											<div class="col-md-6">
												<label for="postal_code" class="">Post code</label>
												<input name="post_code" type="text" class="" id="postal_code" placeholder="">
											</div>
										</div>
										</br>
									</div>
									<h4 class="w500 accordion" data-toggle="collapse" data-target="#meetingpoints">
										<i class="fa fa-angle-right" aria-hidden="true"></i>
										Choose a saved meeting point
									</h4>
									<div id="meetingpoints" class="collapse">
										 <div class="form-group{{ $errors->has('meeting_point') ? ' has-error' : '' }}">
										 	<div class="row">
											 	<div class="col-md-6">
													<label for="meeting_point" class="">Meeting Point</label>
													<select name="meeting_point" class="">
														<option value="">Choose Meeting Point</option>
														@foreach(auth()->user()->profile->meetingPoints as $mp)
															<option value="{{$mp->id}}">{{$mp->address1}}</option>
														@endforeach
													</select>
												</div>

										 	</div>
										 </div>
									</div>
								</div>
							</div>
							<hr>
							<button type="button" id="back-to-products" class="btn btn-primary" data-dismiss="alert">
								<i class="icon icon-left-chevron"></i>
								Previous
							</button>
							<button type="button" id="to-final" class="btn btn-primary" data-dismiss="alert">
								Next
								<i class="icon icon-right-chevron"></i>
							</button>
							</br></br>
						</div>

						<div class="step" id="step3" style="display: none;">
							<h3 class="w500">
								Ready to get your products!
							</h3>
							<p class="s-12em">
								Your shopping cart is now ready to be finalised. You can see an overview of what's in your cart below, as well as leave a message regarding your delivery. After finalising your cart, you will either be offered a delivery by {{$shopping_cart->business->name}}, or a delivery via our crowd delivery platform.
							</p>
							<div class="row">
								<div class="col-md-6">
									<div class="box-light">
										<h4 class="w500 no-vm">
											Shopping cart overview
										</h4>
										<ul class="products-as-list">
											<hr>
											<div class="row">
												@foreach($shopping_cart->items as $item)
												<div class="col-md-12">
													<li>
														<div class="row">
															<div class="col-md-2 col-sm-3 col-xs-3">
																<img class="img-responsive" src="/storage/{{$item->product->picture}}">
															</div>
															<div class="col-md-10 col-sm-9 col-xs-9">
																<h4>
																	{{$item->product->name}}

																</h4>
																<h6>
																	<b>Qty:</b> {{$item->qty}} | € {{$item->price}}
																</h6>
															</div>
														</div>
													</li>
												</div>
												@endforeach
											</div>
										</ul>
										<h3 class="info no-vm">
											<span>
												<i class="icon icon-euro"></i>
												Total
											</span>
											€ {{$shopping_cart->price}}
										</h3>
									</div>
								</div>
								<div class="col-md-6">
									<p class="s-12em">
										Feel free to leave a message regarding your delivery below:
									</p>
									<textarea name="message" id="" cols="30" rows="4"></textarea>
								</div>
								<br>
							</div>
							<div class="text-center">
								
								<button type="submit" class="btn  btn-primary s-14em">
									<i class="icon icon-success"></i>
									Finalise shopping cart
								</button>

							</div>
							<hr>
							<button type="button" id="back-to-location" class="btn btn-primary" data-dismiss="alert">
								<i class="icon icon-left-chevron"></i>
								Previous
							</button>
							</br></br>
						</div>
					</div>
				</form>
			</div>
			{{-- Shopping cart overview --}}
			<div class="col-lg-4">


			</div>
		</div>
	</div>
@endsection


@section('footer')
	@include('partials.footer')
@endsection

@section('scripts')
	@include('partials.scripts')
	<script src="/js/assets/bootstrap-datepicker.js"></script>
	<script src="/js/assets/jquery.timepicker.min.js"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
	<script type="text/javascript" src="/js/products/products.js"></script>
	<script type="text/javascript" src="/js/products/request.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyMYcybGUzLrw4_suuPY-6XdmOk4JZMQY&libraries=places&callback=initAutocomplete" async defer></script>
@endsection