routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// //TEST REDIS
// Route::get('/visits', function () {
//
// dd(App\ProductsCategories::find(23)->fields->first()->name);
//
// });





Route::get('/stripe/charge', function () {
    $invoices = App\DealInvoice::all();

    return view('stripe.charge')->withInvoices($invoices);
});
Route::post('/stripe/charge', 'StripeController@charge');



Route::post('stripe/webhook', 'StripeWebhookController@handle');


Route::get('/', 'HomepageController@home');

//TEST
Route::get('/login-test/{id}', function ($id) {
    Auth::loginUsingId($id);
    return redirect()->back();
});

Route::get('/notifications/test', function () {
  Auth::user()->notify(new \App\Notifications\Business\Welcome);
  return redirect()->back();
});

//Authenticate Links
Auth::routes();
Route::get('/join', function () {
  return redirect('business/register');
});
Route::get('business/register', 'Auth\RegisterBusinessController@showRegistrationForm');
Route::post('business/register', 'Auth\RegisterBusinessController@register');
Route::get('/auth/{provider}', 'Auth\SocialController@redirectToProvider');
Route::get('/auth/callback/{provider}', 'Auth\SocialController@handleProviderCallback');

//Verified Email
Route::get('/verify/{token}', 'UserController@verifiedEmail');

//Referral invitation
Route::get('/invite/{ref}', 'ReferController@invite');


//Authenticate users has access
Route::group(['middleware' => 'auth'], function(){

  //Account Settings
  Route::get('account/settings', 'UserController@accountSettings');
  Route::post('account/settings/password/update', 'UserController@updatePassword');
  Route::post('account/settings/email/update', 'UserController@updateEmail');
  Route::post('account/settings/payout/update', 'UserController@updatePayoutMethods');

  //Notifications
  Route::get('notifications/read/{notification_id}', 'NotificationsController@read');
  Route::get('notifications/markasread', 'NotificationsController@markAsRead');

  //Bids
  Route::get('delivery/{request}/bid/create', 'BidController@create');
  Route::post('delivery/{request}/bid/create', 'BidController@store');

  //Conversation
  Route::get('conversations', 'ConversationController@index');
  Route::get('conversations/{conversation}', 'ConversationController@single');
  Route::post('conversations/{conversation}/sendMessage', 'ConversationController@sendMessage');

  //Deal
  Route::get('deal/{invoice}', 'DealController@index');

});

//Only admin has access
// **For now is auth, change it before public in admin**
Route::group(['middleware' => 'admin'], function(){



  //Products Categories
  Route::get('admin/categories', 'ProductsCategoriesController@index');
  Route::get('admin/categories/create', 'ProductsCategoriesController@create');
  Route::post('admin/categories/create', 'ProductsCategoriesController@store');
  Route::get('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@edit');
  Route::post('admin/categories/{productsCategories}/edit', 'ProductsCategoriesController@update');
  Route::get('admin/categories/{productsCategories}/delete', 'ProductsCategoriesController@destroy');
  Route::get('admin/categories/{productsCategories}/restore', 'ProductsCategoriesController@restore');

  Route::get('admin/businesses/index', 'AdminController@businesses');
  Route::get('admin/clients/index', 'AdminController@users');
  Route::get('admin/payments/index', 'AdminController@payments');
  Route::get('admin/products/index', 'AdminController@products');

  Route::get('admin/products/feature/add/{product}', 'FeaturedProductsController@add');
  Route::get('admin/products/feature/remove/{product}', 'FeaturedProductsController@remove');
  Route::get('feature', 'FeaturedProductsController@getAllFeatured');

});

//Only business has access
Route::group(['middleware' => 'business'], function(){

  //  Dashboard view only for businesses
  Route::get('/dashboard', "BusinessController@dashboard");

  //Themes
  Route::get('business/themes', 'BusinessThemeController@themes');
  Route::post('business/themes', 'BusinessThemeController@updateThemes');
  Route::get('/business/themes/customise', 'BusinessThemeController@customise');
  Route::post('/business/themes/customise/frontpageslider', 'BusinessThemeController@updateFrontPageSlider');
  Route::post('/business/themes/customise/homepage', 'BusinessThemeController@updateHomePage');
  Route::post('/business/themes/customise/aboutpage', 'BusinessThemeController@updateAboutPage');


  //Products
  Route::get('business/products', 'ProductsController@index');
  Route::get('business/products/create', 'ProductsController@create');
  Route::post('business/products/create', 'ProductsController@store');
  Route::get('business/products/{products}/edit', 'ProductsController@edit');
  Route::post('business/products/{products}/edit', 'ProductsController@update');
  Route::get('business/products/{products}/delete', 'ProductsController@destroy');
  Route::get('business/products/{products}/images', 'ProductsController@images');
  Route::post('business/products/{products}/images/add', 'ProductsController@addImages');
  Route::post('business/products/{products}/images/remove', 'ProductsController@removeImages');



  //Stores
  Route::get('business/stores', 'StoresController@index');
  Route::get('business/stores/create', 'StoresController@create');
  Route::post('business/stores/create', 'StoresController@store');
  Route::get('business/stores/{stores}/edit', 'StoresController@edit');
  Route::post('business/stores/{stores}/edit', 'StoresController@update');
  Route::get('business/stores/{stores}/delete', 'StoresController@destroy');


  //ProductsStores
  //store
  Route::get('business/stores/{stores}/products', 'ProductsStoresController@storeProducts');
  Route::get('business/stores/{stores}/products/{product}/add', 'ProductsStoresController@storeAddProduct');
  Route::get('business/stores/{stores}/products/{product}/remove', 'ProductsStoresController@storeRemoveProduct');
  //product
  Route::get('business/products/{products}/stores', 'ProductsStoresController@productStores');
  Route::get('business/products/{products}/stores/{store}/add', 'ProductsStoresController@productAddStore');
  Route::get('business/products/{products}/stores/{store}/remove', 'ProductsStoresController@productRemoveStore');

  //Discount
  Route::get('business/discount/create', 'ProductsDiscountController@create');
  Route::post('business/discount/create', 'ProductsDiscountController@store');
  Route::get('business/discount/{productsDiscount}/remove', 'ProductsDiscountController@destroy');


  //Profile
  Route::get('/business/profile/edit', 'BusinessController@edit');
  Route::post('/business/profile/edit', 'BusinessController@update');
  Route::get('/business/account/payout', 'BusinessController@payout');
  Route::get('/business/account/email', 'BusinessController@changeEmail');
  Route::get('/business/account/password', 'BusinessController@changePwd');

  //Shopping carts
  Route::get('/business/carts', 'ClientRequestController@index');
  Route::get('/business/carts/open', 'ClientRequestController@openCarts');
  Route::get('/business/carts/completed', function(){
    return view('carts.business-closed');
  });
  Route::get('/business/carts/{invoice}/invoice', 'DealController@businessInvoice');
  Route::get('/business/carts/{request}/bid', 'BidController@businessCreate');
  Route::get('/business/carts/{request}/view', 'ShoppingCartController@businessView');

  Route::get('/business/card', 'StripeController@creditCard');
  Route::post('/business/card', 'StripeController@updateCreditCard');


  //Subscription
  Route::get('/business/subscription', 'StripeController@index');
  Route::get('/business/subscription/change', 'StripeController@change_subscription');
  Route::patch('/business/subscription/change', 'StripeController@changePlan');

  Route::delete('/stripe/subscribe', 'StripeController@destroy');
  Route::patch('/stripe/subscribe', 'StripeController@update');

});

Route::get('/stripe/subscribe', function () {
    $plans = App\SubscribePlan::all();

    return view('stripe.subscribe')->withPlans($plans);
});
Route::post('/stripe/subscribe', 'StripeController@register');

//Only clients has access
Route::group(['middleware' => 'client'], function(){
  // Dashboard
  Route::get('/client/dashboard', 'ClientController@dashboard');
  //Profile
  Route::get('/client/profile/edit', 'ClientController@edit');
  Route::post('/client/profile/edit', 'ClientController@update');
  Route::get('/client/profile/settings', 'UserController@accountSettings');
  Route::get('/client/profile/email', 'UserController@changeEmail');
  Route::get('/client/profile/pwd', 'UserController@changePwd');
  Route::get('/client/profile/payout', 'UserController@changePayout');

  //Meeting points
  Route::get('/client/meeting_points', 'MeetingPointsController@index');
  Route::post('/client/meeting_points/create', 'MeetingPointsController@store');
  Route::get('/client/meeting_points/{meeting_points}/delete', 'MeetingPointsController@destroy');
  Route::post('/client/meeting_points/{meeting_points}/edit', 'MeetingPointsController@update');

  //Shopping Cart
  Route::post('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::get('/products/{product}/addItemToCart', 'ItemsController@store');
  Route::post('/products/{product}/addSearchedItemToCart', 'ItemsController@searchAdd');
  Route::get('/item/{item}/remove', 'ItemsController@destroy');
  Route::get('/shopping_cart', 'ShoppingCartController@index');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Wishlist;
use Redis;

class Products extends Model
{
  use SoftDeletes;
  use Wishlist;

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'products';

  protected $softDelete = true;


  public function getSlugAttribute(): string
  {
    return str_slug($this->name);
  }

  public function getUrlAttribute(): string
  {
      return action('ProductsController@single', [$this->id, $this->slug]);
  }

  public function getCurrentpriceAttribute(): string
  {
    if($this->discount){
      $price = $this->discount->new_price;
    }else {
      $price = $this->price;
    }

    return number_format($price, 2, '.', '');
  }

  public function getTagsstringAttribute(): string
  {
    $tags_string = $this->tags()->pluck('name')->implode(', ');

    return $tags_string;
  }

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'name',
    'description',
    'long_description',
    'price',
    'bag',
    'weight',
    'height',
    'width',
    'depth',
    'picture',
    'video',
    'category_id',
    'business_id',
    'status',
    'has_stock'
  ];

  /**
  * Return the relationship with Business model.
  */
  public function business()
  {
    return $this->belongsTo('App\Business', 'business_id');
  }

  /**
  * Return the relationship with Category model.
  */
  public function category()
  {
    return $this->belongsTo('App\ProductsCategories', 'category_id');
  }

  public function tags()
  {
    return $this->BelongsToMany('App\Tags', 'products_tags', 'product_id', 'tag_id');
  }

  public function stores()
  {
    return $this->BelongsToMany('App\Stores', 'products_stores', 'product_id', 'store_id');
  }

  public function hasStore($store)
  {
    return $this->stores()->where('store_id', $store->id)->first()!=null;
  }

  public function syncStores($stores)
  {
    return $this->stores()->sync($stores);
  }

  /**
   * Get the discount record associated with the product.
   */
  public function discount()
  {
      return $this->hasOne('App\ProductsDiscount', 'product_id', 'id');
  }

  public function scopeLive()
  {

    return \DB::table('products')
                ->whereExists(function ($query1) {
                    $query1->select(\DB::raw(1))
                          ->from('business')
                          ->whereRaw('business.id = products.business_id')
                          ->whereRaw('business.status <> "offline"');
                })
                ->get();

    // return $query->where('status', 'live')->orWhere('status', 'edited')->get();
  }

  public function items()
  {
    return $this->hasMany('App\Items', 'product_id');
  }

  public function isFeatured()
  {
    return Redis::zscore('featured', $this->id);
  }

  public function scopeFeatures($query)
  {

    $ids = Redis::zrange('featured', 0, -1);

    // $features = Products::hydrate(
    //   array_map('json_decode', $features)
    // );

    $features = self::whereIn('id', $ids)->get();

    // dd($features);
    return $features;
  }

  public function images()
  {
    $images = Redis::smembers('product'.$this->id.'images');

    return $images;

  }


}

resources/views/products/_edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update Product</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="/business/products/{{$product->id}}/edit" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $product->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Price</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control" name="price" value="{{ $product->price }}" required>

                                @if ($errors->has('price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                            <label for="category_id" class="col-md-4 control-label">Category</label>

                            <div class="col-md-6">
                              <select name="category_id">
                                @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                              </select>
                                @if ($errors->has('category_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Description (textarea)</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control" value="{{ $product->description }}" name="description">

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('picture') ? ' has-error' : '' }}">
                            <label for="picture" class="col-md-4 control-label">Picture</label>

                            <div class="col-md-6">
                                <input id="picture" type="file" name="picture">
                                <img src="{{Storage::url($product->picture)}}">
                                @if ($errors->has('picture'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('picture') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('video') ? ' has-error' : '' }}">
                            <label for="video" class="col-md-4 control-label">Video</label>

                            <div class="col-md-6">
                                <input id="video" type="file" name="video">

                                @if ($errors->has('video'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('video') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('bag') ? ' has-error' : '' }}">
                            <label for="bag" class="col-md-4 control-label">Bag (ex. Cabin)</label>

                            <div class="col-md-6">
                                <input id="bag" type="text" class="form-control" name="bag" value="{{ $product->bag }}">

                                @if ($errors->has('bag'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('bag') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('weight') ? ' has-error' : '' }}">
                            <label for="weight" class="col-md-4 control-label">weight</label>

                            <div class="col-md-6">
                                <input id="weight" type="text" class="form-control" name="weight" value="{{ $product->weight }}">

                                @if ($errors->has('weight'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('weight') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('height') ? ' has-error' : '' }}">
                            <label for="height" class="col-md-4 control-label">height</label>

                            <div class="col-md-6">
                                <input id="height" type="text" class="form-control" name="height" value="{{ $product->height }}">

                                @if ($errors->has('height'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('height') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('width') ? ' has-error' : '' }}">
                            <label for="width" class="col-md-4 control-label">width</label>

                            <div class="col-md-6">
                                <input id="width" type="text" class="form-control" name="width" value="{{ $product->width }}">

                                @if ($errors->has('width'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('width') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('depth') ? ' has-error' : '' }}">
                            <label for="depth" class="col-md-4 control-label">depth</label>

                            <div class="col-md-6">
                                <input id="depth" type="text" class="form-control" name="depth" value="{{ $product->depth }}">

                                @if ($errors->has('depth'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('depth') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                            <label for="tags" class="col-md-4 control-label">Add Tags(seperate with comma)</label>

                            <div class="col-md-6">
                                <input id="tags" type="text" class="form-control" name="tags" value="{{$product->tagsstring}}">

                                @if ($errors->has('tags'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tags') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update Product
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/_request.blade.php
@include('partials.head')

<button type="button" class="quick-action-btn visible-xs">
	<i class="pe-7s-keypad pe-3x pe-va"></i>
</button>

@include('partials.quick-action')

@include('partials.navbar')

{{-- Main --}}
<div class="container first">
	<div class="row">
		{{-- Request steps form --}}
		<div class="col-xs-12 col-md-8 col-lg-8">
			<div class="row">
				<div style="margin-bottom: 150px;">
					<ul class="steps-timeline">
						<li class="active">
							<i class="fa fa-shopping-basket fa-2x" aria-hidden="true"></i>
							<span>
								Quantity
							</span>
						</li>
						<li class="">
							<i class="fa fa-map-marker fa-2x" aria-hidden="true"></i>
							<span>
								Location
							</span>
						</li>
						<li class="">	
							<i class="fa fa-calendar fa-2x" aria-hidden="true"></i>
							<span>
								Time/Date
							</span>
						</li>
						<div class="progress-bar">
						</div>
						<div class="full-bar">
						</div>
					</ul>
					
				</div>

				<div class="steps-form active" id="step1">
					<h2>How many would you like?</h2>
					<p>
						Select how many of 'Product title' you would like to request.
					</p>
					<div class="row product-bar ">
						<div class="col-xs-12 col-lg-3">
							<img class="img-responsive" src="https://placeimg.com/240/240/tech">
							
						</div>
						<div class="col-xs-12 col-lg-9 ">
							<h3>
								<span class="flag-icon flag-icon-cy"></span> &nbsp;
								Really long product title goes here and wraps around too 
								<br>
								<small>
								<i class="fa fa-shopping-bag" aria-hidden="true"></i> Monagri Grape Farm &nbsp; | &nbsp; <i class="fa fa-balance-scale" aria-hidden="true"></i> 300 g
								</small>
								<h2 id="total-price">
									£60.00
								</h2>
							</h3>
							<label for="qty">Quantity:</label>
							<form action="" name="delivery-address">
							<input type="number" min="1" step="1" value="1" name="qty">
							
						</div>
							
					</div>
					<br>
					<div class="alert alert-dismissible alert-info">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						Since you're buying a product from <strong>Monagri Grape Farm</strong>, why not consider adding another product from this company to your shopping cart?
						<br><br>
						<div class="row">
							<div class="col-xs-3 col-md-2 col-lg-1">
								<i class="pe-7s-cart pe-3x pe-va"></i>
							</div>
							<div class="col-xs-9 col-md-10 col-lg-11">
								Products belonging to the same company automatically get added into one shopping cart, so your deliverer can pick them up in one go and deliver them to you!
							</div>
						</div>
						<br>
						<a href="#" class="btn btn-info">Keep shopping</a>
					</div>
					<button type="button" id="to-delivery" class="btn btn-primary" data-dismiss="alert">Next</button>
				</div>
				<div class="steps-form" id="step2">
					<h2>Where would you like it delivered?</h2>
					<p>
						Please fill in the address of where you would like your items delivered.
					</p>
					
					<br>
					
						
					
					<label for="address" class=" control-label">Search for address</label>
					<input type="text" class="form-control" id="address" placeholder="" onFocus="geolocate()">
					<hr>

					<label for="street_number" class=" control-label">Address line 1</label>
					<input type="text" class="form-control" id="street_number" placeholder="">
		
					<label for="route" class=" control-label">Address line 2</label>
					<input type="text" class="form-control" id="route" placeholder="">
					
					<label for="locality" class=" control-label">City</label>
					<input type="text" class="form-control" id="locality" placeholder="">

					<label for="administrative_area_level_1" class=" control-label">State</label>
					<input type="text" class="form-control" id="administrative_area_level_1" placeholder="">

					<label for="country" class=" control-label">Country</label>
					<input type="text" class="form-control" id="country" placeholder="">

					<label for="postal_code" class=" control-label">Post code</label>
					<input type="text" class="form-control" id="postal_code" placeholder="">
					</form>
					<button type="button" id="to-qty" class="btn btn-primary" data-dismiss="alert">Back</button>

					<button type="button" id="to-delivery" class="btn btn-primary" data-dismiss="alert">Next</button>
				</div>
			</div>
			
		</div>
		<!-- Shopping cart overview -->
		<div class="col-xs-12 col-md-4 col-lg-4">
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>
		
	</div>
</div>

<div class="container">
	
</div>
	


</body>
<script type="text/javascript" src="/js/assets/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/js/assets/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/products/products.js"></script>
<script type="text/javascript" src="/js/products/product-request.js"></script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyMYcybGUzLrw4_suuPY-6XdmOk4JZMQY&libraries=places&callback=initAll" async defer></script>
</html>

resources/views/products/images.blade.php
@include('dashboard.head')

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			@include('dashboard.nav')


			<!-- page content -->
			<div class="right_col" role="main">
				<div class="">
					<div class="page-title">
				 		<div class="title_left">
					 		<h2>Products</h2>
				  		</div>


					</div>
					<div class="clearfix"></div>

					<div class="row">
						<div class="col-md-8 col-sm-12 col-xs-12">
							<div class="x_panel">
								<div class="x_title">
									<h2>Add more images to product</h2>

									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<form class="form-horizontal" role="form" method="POST" action="/business/products/{{$product->id}}/images/add" enctype="multipart/form-data">
									{{ csrf_field() }}


									<div class="form-group{{ $errors->has('picture') ? ' has-error' : '' }}">
										<label for="picture" class="col-md-4 col-xs-12 control-label">Image</label>
										<div class="col-md-6 col-xs-12">
											<input id="picture" type="file" name="picture">

											@if ($errors->has('picture'))
											<span class="help-block">
											<strong>{{ $errors->first('picture') }}</strong>
											</span>
											@endif
										</div>
									</div>

									<div class="form-group">
										<div class="col-md-8 col-md-offset-4">
											<button type="submit" class="btn btn-primary">
											Add Image
											</button>
										</div>
									</div>
								</form>


										<hr>
										<p class="text-muted font-13 m-b-30">
											Images of the product
										</p>

										@foreach($product->images() as $img)
											<img class="img-responsive col-md-4" src="/storage/{{$img}}" >
											<form method="POST" action="/business/products/{{$product->id}}/images/remove">
												{{ csrf_field() }}
												<input type="hidden" name="image" value="{{$img}}">
												<button type="submit" class="btn btn-xs btn-danger">Remove</button>
											</form>
										@endforeach


								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-12 col-xs-12">
							<h3>Adding discounts to products</h3>
							<p  class="text-muted font-13 m-b-30">
								Use this page to add a discount to your products. You can choose whether your discount is by percentage, or by value, and also add an expiry for your discount.
							</p>
						</div>
					</div>
				</div>
			</div>


			@include('dashboard.footer')
		</div>
	</div>

	@include('dashboard.scripts')
	<script type="text/javascript" src="/js/assets/jquery.tagsinput.js"></script>
	<script type="text/javascript">
		$(function(){

			$('.datepicker').datepicker({
				format: 'yyyy-mm-dd'
			});
		});

	</script>
</body>
</html>